apiVersion: v1
kind: Service
metadata:
  name: {{ template "sadis-server.fullname" . }}
  labels:
    app: {{ template "sadis-server.name" . }}
    chart: {{ template "sadis-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.sadis_server.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "sadis-server.name" . }}
    release: {{ .Release.Name }}
